name: iosApp
options:
  bundleIdPrefix: com.ovasta.sellers
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  createIntermediateBuildFilesDirectory: false

settings:
  CODE_SIGN_STYLE: Manual
  CODE_SIGN_IDENTITY: "-"
  DEVELOPMENT_TEAM: H8X427WWQW
  SWIFT_VERSION: "5.9"

targets:
  iosApp:
    type: application
    platform: iOS
    sources:
      - path: iosApp
        excludes:
          - "**/*.xcodeproj"
          - "**/*.xcworkspace"
          - "Pods"
    settings:
      base:
        PRODUCT_NAME: "Ovasta Sellers"
        PRODUCT_BUNDLE_IDENTIFIER: com.ovasta.sellers
        INFOPLIST_FILE: iosApp/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: false
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SUPPORTS_MACCATALYST: false
    dependencies:
      - sdk: UIKit.framework
      - sdk: SwiftUI.framework
      - sdk: Combine.framework
      - cocoaPods: shared
      - cocoaPods: FirebaseCore
      - cocoaPods: FirebaseAuth
      - cocoaPods: FirebaseFirestore
      - cocoaPods: FirebaseMessaging
      - cocoaPods: FirebaseCrashlytics
